"""Add final detailed client columns

Revision ID: b7ed69d93feb
Revises: 
Create Date: 2025-09-13 18:26:54.125972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ed69d93feb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('premium_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('premium_frequency', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('expiration_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('expiration_date')
        batch_op.drop_column('premium_frequency')
        batch_op.drop_column('premium_amount')
        batch_op.drop_column('policy_id')

    # ### end Alembic commands ###
